### ISSUE TITLE
Consider making the `PackedObjectReader` seekable

### ISSUE THREAD

**Issue by sphuber** [giovannipizzi/disk-objectstore#56]
I understand why the `PackedObjectReader` is currently not seekable in order to not let bytes be read that do not belong to the object for which the reader was requested. However, some applications might still want to seek back to the beginning of the byte stream after having consumed some or all bytes of the object. Example might be where a client wants to write the content of the object to disk using the checksum of the content as the filename. The most efficient way to do this is first creating the checksum from the stream, before seeking back to the beginning and writing the content to disk. The workarounds are either inefficient, involving a temporary file on disk, or complicated, by constructing some reader class that automatically redirects the bytes in two directions. Would it not be possible to allow `seek` but just like `read` raise when the boundaries are surpassed?

**Comment by giovannipizzi** [comment]
This should be quite straightforward.

I would avoid allowing seeking when writing: this would make indeed hask calculation a mess. 

But I think the use case here is almost always the `PackedObjectReader` where no hashing needs to be computed.

Implementing the seek at this level is really easy, I already have guards to avoid going beyond bounds, and I keep track of the offset. 

The thing to think about is the case of compressed packed objects.
I think the use case is important enough to provide seek even if inefficient. The simple implementation in this case can just seek back to zero (easy) and read the correct number of bytes. This of course means re reading everything and uncompressing. But unless there is some clever way to seek in a zipped format in a clever way (I'll check) i don't see many ways around. The important thing is to avoid to use read() to seek if the object is not compressed, as that seek can be much more efficient. But this should be OK because anyway these will be two seek implementation on two different classes (the second one is on the compressed object wrapper).

**Comment by giovannipizzi** [comment]
[Here](https://zlib.net/manual.html) it mentions indeed that the gzseek function exists but it's very inefficient for read mode - I guess it's implemented as I mention above.

**Comment by giovannipizzi** [comment]
For `zlib` one could exploit the [`copy` method](https://zlib.net/manual.html) of the `decompressobj`. One needs to check the overhead, but one could eg decide that it's acceptable to re-decompress, say, up to 100MB of data, and store a copy of the object every 100MB in an internal list. When asked to seek, one would find the closest saved copy before the position that was asked and decompress from there.

However the implementation is non trivial (but doable). But it's only for efficiency so I would start implementing theslow but simple seek, and then we move these comments to a different issue about performance. 

Another note: we need to check if the `copy` method is provided also by other compression libraries that weight want to use.
